version: '3.9'

services:
  web_app:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped